name: "Hello Actions"
description: "Greet Someone"
author: "octocat@gitnhub.com"

inputs:
  MY_Name:
    description: "Who to greet"
    required: true
    default: "World"
runs:
  using: "docker"
  image: "Dockerfile"
   
branding:
  icon: "mic"
  color: "purple"
